"""empty message

Revision ID: 7bfcc688e99d
Revises: 
Create Date: 2017-05-20 20:37:10.032803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfcc688e99d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlists',
    sa.Column('item_ID', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_ID')
    )
    op.create_table('person',
    sa.Column('person_ID', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=50), nullable=False),
    sa.Column('person_email', sa.String(length=255), nullable=False),
    sa.Column('Person_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('person_ID'),
    sa.UniqueConstraint('person_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('bucketlists')
    # ### end Alembic commands ###
